class Countries < ActiveRecord::Migration
  def self.up
  create_table :countries do |t|
  t.string	:symbol
  t.string	:name
  t.timestamps
  end
  Country.create :symbol => "A", :name => "Austria"
  Country.create :symbol => "AFG" , :name => "Afghanistan" 
  Country.create :symbol => "AG" , :name => "Antigua and Barbuda"
  Country.create :symbol => "AL" , :name => "Albania"
  Country.create :symbol => "AND" , :name => "Andorra" 
  Country.create :symbol => "ANG" , :name => "Angola" 
  Country.create :symbol => "ARK" ,:name => "Antarctica" 
  Country.create :symbol => "AM" , :name => "Armenia" 
  Country.create :symbol => "ARU" , :name => "Aruba" 
  Country.create :symbol => "AUS" , :name => "Australia" 
  Country.create :symbol => "AX" , :name => "Åland Islands" 
  Country.create :symbol => "AXA" , :name => "Anguilla" 
  Country.create :symbol => "AZ" , :name => "Azerbaijan" 
  Country.create :symbol => "B" , :name => "Belgium" 
  Country.create :symbol => "BD" , :name => "Bangladesh" 
  Country.create :symbol => "BDS" , :name => "Barbados" 
  Country.create :symbol => "BF" , :name => "Burkina Faso" 
  Country.create :symbol => "BG" , :name => "Bulgaria" 
  Country.create :symbol => "BHT" , :name => "Bhutan" 
  Country.create :symbol => "BIH" , :name => "Bosnia and Herzegovina"
  Country.create :symbol => "BOL" , :name => "Bolivia" 
  Country.create :symbol => "BR" , :name => "Brazil" 
  Country.create :symbol => "BRN" , :name => "Bahrain" 
  Country.create :symbol => "BRU" , :name => "Brunei" 
  Country.create :symbol => "BS" , :name => "Bahamas" 
  Country.create :symbol => "BU" , :name => "Burundi" 
  Country.create :symbol => "BY" , :name => "Belarus" 
  Country.create :symbol => "BZ" , :name => "Belize" 
  Country.create :symbol => "C" , :name => "Cuba" 
  Country.create :symbol => "CAM" , :name => "Cameroon" 
  Country.create :symbol => "CDN" , :name => "Canada" 
  Country.create :symbol => "CGO" , :name => "Democratic Republic of the Congo"
  Country.create :symbol => "CH" , :name => "Switzerland"
  Country.create :symbol => "CI" , :name => "Côte d'Ivoire (Ivory Coast)"
  Country.create :symbol => "CL" , :name => "Sri Lanka"
  Country.create :symbol => "CN" , :name => "People's Republic of China"
  Country.create :symbol => "CO" , :name => "Colombia"
  Country.create :symbol => "COM" , :name => "Comoros"
  Country.create :symbol => "CR" , :name => "Costa Rica" 
  Country.create :symbol => "CV" , :name => "Cape Verde" 
  Country.create :symbol => "CY" , :name => "Cyprus" 
  Country.create :symbol => "CYM" , :name => "Wales" 
  Country.create :symbol => "CZ" , :name => "Czech Republic" 
  Country.create :symbol => "D" , :name => "Germany" 
  Country.create :symbol => "DJI" , :name => "Djibouti" 
  Country.create :symbol => "DK" , :name => "Denmark" 
  Country.create :symbol => "DOM" , :name => "Dominican Republic" 
  Country.create :symbol => "DY" , :name => "Benin" 
  Country.create :symbol => "DZ" , :name => "Algeria" 
  Country.create :symbol => "E" , :name => "Spain" 
  Country.create :symbol => "EAK" , :name => "Kenya" 
  Country.create :symbol => "EAT" , :name => "Tanzania" 
  Country.create :symbol => "EAU" , :name => "Uganda" 
  Country.create :symbol => "EC" , :name => "Ecuador" 
  Country.create :symbol => "ENG" , :name => "England" 
  Country.create :symbol => "ER" , :name => "Eritrea" 
  Country.create :symbol => "ES" , :name => "El Salvador" 
  Country.create :symbol => "EST" , :name => "Estonia" 
  Country.create :symbol => "ET" , :name => "Egypt" 
  Country.create :symbol => "ETH" , :name => "Ethiopia" 
  Country.create :symbol => "F" , :name => "France" 
  Country.create :symbol => "FIN" , :name => "Finland" 
  Country.create :symbol => "FJI" , :name => "Fiji" 
  Country.create :symbol => "FL" , :name => "Liechtenstein" 
  Country.create :symbol => "FO" , :name => "Faroe Islands" 
  Country.create :symbol => "FSM" , :name => "Federated States of Micronesia" 
  Country.create :symbol => "G" , :name => "Gabon" 
  Country.create :symbol => "GB" , :name => "United Kingdom"
  Country.create :symbol => "GBA" , :name => "Alderney" 
  Country.create :symbol => "GBG" , :name => "Guernsey"
  Country.create :symbol => "GBJ" , :name => "Jersey" 
  Country.create :symbol => "GBM" , :name => "Isle of Man" 
  Country.create :symbol => "GBZ" , :name => "Gibraltar" 
  Country.create :symbol => "GCA" , :name => "Guatemala" 
  Country.create :symbol => "GE" , :name => "Georgia" 
  Country.create :symbol => "GH" , :name => "Ghana" 
  Country.create :symbol => "GQ", :name => "Equatorial Guinea" 
  Country.create :symbol => "GR" , :name => "Greece" 
  Country.create :symbol => "GUY" , :name => "Guyana" 
  Country.create :symbol => "H" , :name => "Hungary" 
  Country.create :symbol => "HK" , :name => "Hong Kong" 
  Country.create :symbol => "HKJ" , :name => "Jordan" 
  Country.create :symbol => "HN" , :name => "Honduras" 
  Country.create :symbol => "HR" , :name => "Croatia" 
  Country.create :symbol => "I" , :name => "Italy" 
  Country.create :symbol => "IL" , :name => "Israel" 
  Country.create :symbol => "IND" , :name => "India" 
  Country.create :symbol => "IR" , :name => "Iran" 
  Country.create :symbol => "IRL" , :name => "Ireland" 
  Country.create :symbol => "IRQ" , :name => "Iraq" 
  Country.create :symbol => "IS" , :name => "Iceland" 
  Country.create :symbol => "J" , :name => "Japan" 
  Country.create :symbol => "JA" , :name => "Jamaica" 
Country.create :symbol => "K" , :name => "Cambodia" 
Country.create :symbol => "KAN", :name => "Saint Kitts and Nevis" 
Country.create :symbol => "KN", :name => "Greenland" 
Country.create :symbol => "KOS" , :name => "Kosovo" 
Country.create :symbol => "KS" , :name => "Kyrgyzstan" 
Country.create :symbol => "KIR" , :name => "Kiribati" 
Country.create :symbol => "KP", :name => "Democratic People's Republic of Korea" 
Country.create :symbol => "KSA" , :name => "Saudi Arabia" 
Country.create :symbol => "KWT" , :name => "Kuwait" 
Country.create :symbol => "KZ" , :name => "Kazakhstan" 
Country.create :symbol => "L" , :name => "Luxembourg" 
Country.create :symbol => "LAO" , :name => "Laos" 
Country.create :symbol => "LAR" , :name => "Libya" 
Country.create :symbol => "LB", :name => "Liberia" 
Country.create :symbol => "LS" , :name => "Lesotho" 
Country.create :symbol => "LT" , :name => "Lithuania" 
Country.create :symbol => "LV" , :name => "Latvia" 
Country.create :symbol => "M" , :name => "Malta" 
Country.create :symbol => "MA" , :name => "Morocco" 
Country.create :symbol => "MAL" , :name => "Malaysia" 
Country.create :symbol => "MC" , :name => "Monaco" 
Country.create :symbol => "MD" , :name => "Moldova" 
Country.create :symbol => "MEX" , :name => "Mexico" 
Country.create :symbol => "MGL" , :name => "Mongolia" 
Country.create :symbol => "MH" , :name => "Marshall Islands" 
Country.create :symbol => "MK" , :name => "Macedonia" 
Country.create :symbol => "MNE" , :name => "Montenegro" 
Country.create :symbol => "MO" , :name => "Macau" 
Country.create :symbol => "MOC" , :name => "Mozambique" 
Country.create :symbol => "MS" , :name => "Mauritius" 
Country.create :symbol => "MV", :name => "Maldives" 
Country.create :symbol => "MW" , :name => "Malawi" 
Country.create :symbol => "MYA" , :name => "Myanmar" 
Country.create :symbol => "N" , :name => "Norway" 
Country.create :symbol => "NA" , :name => "Netherlands Antilles" 
Country.create :symbol => "NAM" , :name => "Namibia" 
Country.create :symbol => "NAU" , :name => "Nauru" 
Country.create :symbol => "NC" , :name => "New Caledonia" 
Country.create :symbol => "NEP", :name => "Nepal" 
Country.create :symbol => "NIC" , :name => "Nicaragua" 
Country.create :symbol => "NI",:name => "Northern Ireland" 
Country.create :symbol => "NL" , :name => "Netherlands" 
Country.create :symbol => "NZ" , :name => "New Zealand" 
Country.create :symbol => "OM" , :name => "Oman" 
Country.create :symbol => "P" , :name => "Portugal" 
Country.create :symbol => "PA" , :name => "Panama" 
Country.create :symbol => "PAK" , :name => "Pakistan" 
Country.create :symbol => "PAL" , :name => "Palau" 
Country.create :symbol => "PE" , :name => "Peru" 
Country.create :symbol => "PL" , :name => "Poland" 
Country.create :symbol => "PMR", :name => "Transnistria" 
Country.create :symbol => "PNG", :name => "Papua New Guinea" 
Country.create :symbol => "PR" , :name => "Puerto Rico" 
Country.create :symbol => "PS" , :name => "Palestinian Authority" 
Country.create :symbol => "PY" , :name => "Paraguay" 
Country.create :symbol => "Q", :name => "Qatar" 
Country.create :symbol => "RA" , :name => "Argentina" 
Country.create :symbol => "RB" , :name => "Botswana" 
Country.create :symbol => "RC" , :name => "Republic of China (Taiwan)" 
Country.create :symbol => "RCA" , :name => "Central African Republic" 
Country.create :symbol => "RCB" , :name => "Republic of the Congo" 
Country.create :symbol => "RCH" , :name => "Chile" 
Country.create :symbol => "RG" , :name => "Guinea" 
Country.create :symbol => "RH" , :name => "Haiti" 
Country.create :symbol => "RI" , :name => "Indonesia" 
Country.create :symbol => "RIM" , :name => "Mauritania" 
Country.create :symbol => "RL" , :name => "Lebanon" 
Country.create :symbol => "RM" , :name => "Madagascar" 
Country.create :symbol => "RMM" , :name => "Mali" 
Country.create :symbol => "RN" , :name => "Niger" 
Country.create :symbol => "RO" , :name => "Romania" 
Country.create :symbol => "ROK" , :name => "Republic of Korea" 
Country.create :symbol => "ROU" , :name => "Uruguay" 
Country.create :symbol => "RP" , :name => "Philippines" 
Country.create :symbol => "RSM" , :name => "San Marino" 
Country.create :symbol => "RT" , :name => "Togo" 
Country.create :symbol => "RUS" , :name => "Russia" 
Country.create :symbol => "RWA" , :name => "Rwanda" 
Country.create :symbol => "S" , :name => "Sweden" 
Country.create :symbol => "SA" , :name => "Saudi Arabia" 
Country.create :symbol => "SCO", :name => "Scotland" 
Country.create :symbol => "SD" , :name => "Swaziland" 
Country.create :symbol => "SGP" , :name => "Singapore" 
Country.create :symbol => "SK" , :name => "Slovakia" 
Country.create :symbol => "SLE", :name => "Sierra Leone" 
Country.create :symbol => "SLO" , :name => "Slovenia" 
Country.create :symbol => "SME" , :name => "Suriname" 
Country.create :symbol => "SMOM" , :name => "Sovereign Military Order of Malta" 
Country.create :symbol => "SN" , :name => "Senegal" 
Country.create :symbol => "SO" , :name => "Somalia" 
Country.create :symbol => "SOL" , :name => "Solomon Islands" 
Country.create :symbol => "SRB" , :name => "Serbia" 
Country.create :symbol => "STP" , :name => "São Tomé and Príncipe" 
Country.create :symbol => "SUD" , :name => "Sudan" 
Country.create :symbol => "SY" , :name => "Seychelles" 
Country.create :symbol => "SYR" , :name => "Syria" 
Country.create :symbol => "T" , :name => "Thailand" 
Country.create :symbol => "TCH", :name => "Chad" 
Country.create :symbol => "TG" , :name => "Togo" 
Country.create :symbol => "TJ" , :name => "Tajikistan" 
Country.create :symbol => "TL" , :name => "Timor-Leste" 
Country.create :symbol => "TM" , :name => "Turkmenistan" 
Country.create :symbol => "TN" , :name => "Tunisia" 
Country.create :symbol => "TO" , :name => "Tonga" 
Country.create :symbol => "TR" , :name => "Turkey" 
Country.create :symbol => "TT" , :name => "Trinidad and Tobago" 
Country.create :symbol => "TUV" , :name => "Tuvalu" 
Country.create :symbol => "UA" , :name => "Ukraine" 
Country.create :symbol => "UAE" , :name => "United Arab Emirates" 
Country.create :symbol => "USA" , :name => "United States" 
Country.create :symbol => "UZ" , :name => "Uzbekistan" 
Country.create :symbol => "V" , :name => "Vatican City" 
Country.create :symbol => "VN" , :name => "Vietnam" 
Country.create :symbol => "VU" , :name => "Vanuatu" 
Country.create :symbol => "WAG" , :name => "Gambia" 
Country.create :symbol => "WAL" , :name => "Sierra Leone" 
Country.create :symbol => "WAN" , :name => "Nigeria" 
Country.create :symbol => "WD" , :name => "Dominica" 
Country.create :symbol => "WG" , :name => "Grenada" 
Country.create :symbol => "WL" , :name => "Saint Lucia" 
Country.create :symbol => "WS" , :name => "Samoa" 
Country.create :symbol => "WSA",:name => "Western Sahara" 
Country.create :symbol => "WV" , :name => "Saint Vincent and the Grenadines" 
Country.create :symbol => "YEM" , :name => "Yemen" 
Country.create :symbol => "YV" , :name => "Venezuela" 
Country.create :symbol => "Z" , :name => "Zambia" 
Country.create :symbol => "ZA" , :name => "South Africa" 
Country.create :symbol => "ZW" , :name => "Zimbabwe" 
end

  def self.down
  drop_table :countries
  end
end
